In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from typing import Dict, List, Any
from sklearn.metrics import precision_score#, recall_score, f1_score, roc_auc_score

from src.counterfactual_fraud_model import (
    OffPolicyEvaluationPipeline,
    OffPolicyEvaluationConfig,
    DataGeneratorConfig,
    LoggingPolicyConfig,
    CounterfactualEstimatorConfig,
    PipelineConfig
)

In [ ]:
# Create configuration for the pipeline
config = OffPolicyEvaluationConfig(
    data_generator=DataGeneratorConfig(
        # HACK: erase later
        sample_size=10_000,
        random_state=223
    ),
    logging_policy=LoggingPolicyConfig(
        cutoff=0.1,
        exploration_rate=0.05, 
        random_state=223
    ),
    counterfactual_estimator=CounterfactualEstimatorConfig(random_state=223),
    pipeline=PipelineConfig(include_data=True)
)

# Initialize pipeline with configuration
pipeline = OffPolicyEvaluationPipeline(config)

In [36]:
results = pipeline.run_pipeline(cutoff=0.3, exploration_rate=0.05, include_data=True)

In [37]:
investigate = results['data']
investigate.head()

   model_scores  is_fraud  propensity_score model_action policy_action
0      0.056512         0               1.0        allow         allow
1      0.084480         0               1.0        allow         allow
2      0.662165         0               0.0        block         block
3      0.012744         0               1.0        allow         allow
4      0.000006         0               1.0        allow         allow

In [38]:
investigate.groupby(['model_action', 'policy_action']).size()

model_action  policy_action
allow         allow            9470
block         allow              21
              block             509
dtype: int64

In [39]:
y_true = investigate['is_fraud']
y_pred = (investigate['model_action'] == 'block').astype(int)

precision_score(y_true, y_pred)

0.18867924528301888

In [43]:
filtered_data = investigate[investigate['policy_action'] == 'allow']

y_true = filtered_data['is_fraud']
y_pred = (filtered_data['model_action'] == 'block').astype(int)
weights = 1 / filtered_data['propensity_score']

precision_score(y_true, y_pred)

0.2857142857142857

In [44]:
filtered_data[filtered_data['propensity_score'] != 1]

      model_scores  is_fraud  propensity_score model_action policy_action
46        0.360226         0              0.05        block         allow
1435      0.341580         0              0.05        block         allow
1611      0.385575         0              0.05        block         allow
2017      0.731744         0              0.05        block         allow
2536      0.469460         0              0.05        block         allow
3681      0.744622         0              0.05        block         allow
4011      0.447179         1              0.05        block         allow
4088      0.684527         0              0.05        block         allow
4312      0.642192         1              0.05        block         allow
5041      0.307551         0              0.05        block         allow
5598      0.947501         1              0.05        block         allow
5675      0.376750         0              0.05        block         allow
6477      0.632984         0              0.05        block         allow
6591      0.439349         1              0.05        block         allow
6702      0.588978         1              0.05        block         allow
7269      0.565498         1              0.05        block         allow
7911      0.504377         0              0.05        block         allow
9078      0.768680         0              0.05        block         allow
9102      0.467608         0              0.05        block         allow
9365      0.346014         0              0.05        block         allow
9682      0.461690         0              0.05        block         allow

In [46]:
results['ope_metrics']

{'precision': {'estimate': 0.045037109633592275,
  'std_error': 0.0021068730512994456,
  'ci_lower': 0.04089590569861466,
  'ci_upper': 0.049182187829153866,
  'bootstrap_samples': [0.04242296327564373,
   0.04276211593284764,
   0.04583377336571972,
   0.042753087723002216,
   0.04563219604943488,
   0.04435526454747069,
   0.04265202702702703,
   0.04743291781111346,
   0.04308797127468582,
   0.04454295967912181,
   0.04400590966652596,
   0.04612137203166227,
   0.04433653541644674,
   0.04552175749894381,
   0.04922881893091063,
   0.043157117231191304,
   0.04634712837837838,
   0.04424965677473862,
   0.04517627190204771,
   0.04381797064723894,
   0.04739786762377283,
   0.04381334459459459,
   0.04149070945945946,
   0.04140699271152424,
   0.045497730391639395,
   0.04109878499735869,
   0.0426430230103441,
   0.04703519712503964,
   0.05114116652578191,
   0.04277566539923954,
   0.04151262279497201,
   0.0439328334565424,
   0.04051915163026274,
   0.044620253164556964,
   0.04624155405405406,
   0.045713682432432436,
   0.047417889956700814,
   0.043625224463927324,
   0.048116492560937,
   0.04350121423292155,
   0.04517150395778364,
   0.044428028704094555,
   0.0474279074680469,
   0.04383648463082286,
   0.042397969972510045,
   0.04539216721207643,
   0.04065469904963041,
   0.04668356569497254,
   0.04454295967912181,
   0.045094518956595206,
   0.04369854338188727,
   0.0437447168216399,
   0.04677436384753458,
   0.046256204456648006,
   0.04814697497624327,
   0.0450849963045085,
   0.04698553479041284,
   0.04370777027027027,
   0.04743291781111346,
   0.04557442768224496,
   0.04369445619974609,
   0.04657794676806084,
   0.03865244481993875,
   0.0444796619123085,
   0.04438807863031072,
   0.043795620437956206,
   0.045497730391639395,
   0.04519058177594763,
   0.044359949302915085,
   0.04754358161648178,
   0.04434589800443459,
   0.04487856388595565,
   0.0429732868757259,
   0.04317989864864865,
   0.04519058177594763,
   0.044648511716276124,
   0.04659763313609468,
   0.040038030847242764,
   0.043386466800380025,
   0.04454766177557268,
   0.04200084423807514,
   0.04379022897541416,
   0.04371700105596621,
   0.045584045584045586,
   0.0444796619123085,
   0.046236672648580175,
   0.045603293571202366,
   0.044801352493660185,
   0.0440337909186906,
   0.045468931321869396,
   0.04213750132009716,
   0.042155309033280505,
   0.04594423320659062,
   0.044974662162162164,
   0.040751689189189186,
   0.04664415365132968,
   0.04372161791107826,
   0.04627086414536235,
   0.04793074324324324,
   0.048342833016677224,
   0.043909647456195904,
   0.0426610348468849,
   0.04296875,
   0.044244984160506866,
   0.04491176159780196,
   0.041385135135135136,
   0.04794592882036118,
   0.04539695945945946,
   0.042436398184313315,
   0.04193514312876307,
   0.046749683410721825,
   0.044561774023231256,
   0.04426835710512414,
   0.041301362628076474,
   0.04655827702702703,
   0.04720168954593453,
   0.044667370644139386,
   0.04340937896070976,
   0.04423097223688378,
   0.0426610348468849,
   0.04655336218726908,
   0.04393747359526827,
   0.043381887270424316,
   0.04331290935981407,
   0.045017436330973264,
   0.04665400042220815,
   0.04318901795142555,
   0.045497730391639395,
   0.0466786355475763,
   0.043115291133889885,
   0.043625224463927324,
   0.04606931530008453,
   0.0475034308033358,
   0.04548812664907652,
   0.042348716865561305,
   0.04591998310989127,
   0.04705011630365828,
   0.0427801837963452,
   0.04702028740490279,
   0.044139387539598736,
   0.04084863837872071,
   0.044552364864864864,
   0.04612137203166227,
   0.046573027774844226,
   0.048664625778528446,
   0.04643799472295514,
   0.043799472295514515,
   0.044993662864385296,
   0.04582893347412883,
   0.04392819429778247,
   0.04523834689779093,
   0.042014145466061435,
   0.04549292801351066,
   0.04585798816568047,
   0.04405239805620114,
   0.04606931530008453,
   0.04487382536163024,
   0.04348743930757864,
   0.04411609498680739,
   0.0470960929250264,
   0.045080236486486486,
   0.04688985109304045,
   0.044148711449091674,
   0.04426368054088316,
   0.04710604140261935,
   0.04436932178322417,
   0.042744063324538256,
   0.04624155405405406,
   0.04614572333685322,
   0.04752349772943289,
   0.043299186820149965,
   0.041939573209380944,
   0.044465568229826787,
   0.04773975496408957,
   0.04423097223688378,
   0.045017436330973264,
   0.04625131995776135,
   0.04805661174482467,
   0.04222081486172683,
   0.04646742000211215,
   0.04402449324324324,
   0.045526565965987115,
   0.04353338968723584,
   0.04560810810810811,
   0.04267455371289743,
   0.044364635048061686,
   0.044993662864385296,
   0.04698057432432432,
   0.0420752926289149,
   0.045593667546174145,
   0.0445994504333122,
   0.046688496883912536,
   0.04278470314810902,
   0.044993662864385296,
   0.04583861427967892,
   0.042014145466061435,
   0.04793580403336501,
   0.044244984160506866,
   0.04782516891891892,
   0.04193514312876307,
   0.04944532488114105,
   0.04809725158562368,
   0.046265976550121476,
   0.04570885675076533,
   0.0415257819103973,
   0.04100612978228704,
   0.04605471638322594,
   0.04730229120473023,
   0.05045387375976356,
   0.048463731390560656,
   0.04326263585522845,
   0.04011400823392801,
   0.0471967057332911,
   0.04656319290465632,
   0.0492184199408534,
   0.04391428269819487,
   0.044561774023231256,
   0.04606931530008453,
   0.044139387539598736,
   0.04548812664907652,
   0.04255993241102545,
   0.04730728616684266,
   0.04529616724738676,
   0.044139387539598736,
   0.0452240067624683,
   0.04773975496408957,
   0.043482849604221635,
   0.042753087723002216,
   0.04715189873417722,
   0.044456177402323126,
   0.04611650485436893,
   0.04443740764196749,
   0.04400126622348845,
   0.04691958152805664,
   0.04256442754541614,
   0.04506596306068602,
   0.044667370644139386,
   0.044888043937473594,
   0.04517627190204771,
   0.0433635788140958,
   0.04350121423292155,
   0.04401055408970976,
   0.04296875,
   0.04656319290465632,
   0.042629524111005596,
   0.043726235741444866,
   0.04444679054054054,
   0.04467208786566691,
   0.04582893347412883,
   0.0457233368532207,
   0.04804138950480414,
   0.045588856057408186,
   0.04526748971193416,
   0.048564189189189186,
   0.044359949302915085,
   0.04900200654768191,
   0.04573299535276722,
   0.045291385135135136,
   0.04465322495513565,
   0.045070719864893395,
   0.046155471060414024,
   0.04413472706155633,
   0.04487382536163024,
   0.048680042238648365,
   0.04644289634789951,
   0.04802617690521427,
   0.04360679970436068,
   0.04454295967912181,
   0.04643799472295514,
   0.04487856388595565,
   0.044216969185310255,
   0.04447496302556518,
   0.04496516782773907,
   0.04688985109304045,
   0.04390037990713381,
   0.042656530461408514,
   0.04445148347587372,
   0.04595879556259905,
   0.042665540183757525,
   0.04457589521495722,
   0.03939585973806506,
   0.0466490765171504,
   0.04582893347412883,
   0.0419573028957937,
   0.0457233368532207,
   0.04474934036939314,
   0.04749841671944269,
   0.04401055408970976,
   0.042789223454833596,
   0.045949086299778175,
   0.04357459379615953,
   0.04401519949335022,
   0.048664625778528446,
   0.040223817567567564,
   0.04605958166068033,
   0.04138950480413895,
   0.04854881266490765,
   0.045593667546174145,
   0.047608993982898765,
   0.04478715538185275,
   0.0462269129287599,
   0.04371238517579981,
   0.044317822095599875,
   0.04643309413254538,
   0.044341216216216214,
   0.0454065469904963,
   0.04615059668391593,
   0.0426610348468849,
   0.0472972972972973,
   0.049720257574158135,
   0.04479188675258821,
   0.046010975094976786,
   0.04807692307692308,
   0.04719172297297297,
   0.048600105652403594,
   0.0469706565336711,
   0.04824375793482861,
   0.04687994931897371,
   0.04465322495513565,
   0.04311073541842773,
   0.04634712837837838,
   0.04413472706155633,
   0.04487856388595565,
   0.04605471638322594,
   0.040734487125369354,
   0.046405919661733616,
   0.04528660403251346,
   0.045867681251321075,
   0.04417203846560287,
   0.04332664060023248,
   0.04708117808508392,
   0.0467990703570674,
   0.048242373060276574,
   0.04530573450205935,
   0.044350580781414996,
   0.04445148347587372,
   0.04675955245936247,
   0.0430414551607445,
   0.04095419041587502,
   0.046111638704231295,
   0.045627376425855515,
   0.04548332629801604,
   0.04632756437315323,
   0.04639120786220015,
   0.044359949302915085,
   0.04576199534982033,
   0.048162230671736375,
   0.04776497939342703,
   0.047674418604651166,
   0.044139387539598736,
   0.03919290090851468,
   0.04031236808780076,
   0.04551214361140443,
   0.04340021119324182,
   0.04393747359526827,
   0.04411609498680739,
   0.04289034439045003,
   0.04543053354463814,
   0.04351499788762146,
   0.046688496883912536,
   0.046462513199577615,
   0.04013519222644698,
   0.04489752799492922,
   0.04539216721207643,
   0.04550733819026502,
   0.046673706441393875,
   0.04752349772943289,
   0.04595394041833932,
   0.04380409541904159,
   0.04438807863031072,
   0.04433653541644674,
   0.043808719518631904,
   0.04818258664412511,
   0.04498891118386313,
   0.04307887234716503,
   0.04295967912180705,
   0.04753855905345447,
   0.04538258575197889,
   0.04173269941891178,
   0.044763513513513514,
   0.04443740764196749,
   0.04688985109304045,
   0.04199198143068158,
   0.0419174321613346,
   0.046261089987325726,
   0.04777507663037734,
   0.043905013192612134,
   0.046688496883912536,
   0.04443271767810027,
   0.04358379062895736,
   0.04318901795142555,
   0.04182509505703422,
   0.04796112402281851,
   0.049292801351066076,
   0.04666877837609545,
   0.04570885675076533,
   0.04498416050686378,
   0.04779993668882558,
   0.044057052297939776,
   0.04445148347587372,
   0.04487856388595565,
   0.04591998310989127,
   0.04858983838597233,
   0.05025337837837838,
   0.047377862192677006,
   0.043386466800380025,
   0.047342280460741834,
   0.0469706565336711,
   0.042155309033280505,
   0.04433653541644674,
   0.04887575213765439,
   0.046126240236436564,
   0.04661733615221987,
   0.04584829917599831,
   0.04458060426790619,
   0.04821692340156151,
   0.04432717678100264,
   0.04468152529840499,
   0.045243128964059194,
   0.042238648363252376,
   0.042238648363252376,
   0.04326720135078092,
   0.041618252878419776,
   0.050543420913791284,
   0.048383688992182546,
   0.045468931321869396,
   0.049646139220449984,
   0.047634136037177865,
   0.04475406375343044,
   0.04542573420663427,
   0.043478260869565216,
   0.04691958152805664,
   0.0418030191069355,
   0.04457118715673849,
   0.046079053054322555,
   0.04839902779245482,
   0.043620616814533164,
   0.047076208570825416,
   0.04447496302556518,
   0.03980992608236537,
   0.04423097223688378,
   0.04771959459459459,
   0.04548812664907652,
   0.0466490765171504,
   0.04422630356765886,
   0.04363444268357105,
   0.04317989864864865,
   0.04337730870712401,
   0.04700042247570765,
   0.045185810810810814,
   0.04720168954593453,
   0.04329004329004329,
   0.044493764531811454,
   0.0471967057332911,
   0.044869087837837836,
   0.04302780420763294,
   0.04969927192149414,
   0.04259141830479814,
   0.0418030191069355,
   0.04666385135135135,
   0.04170185810810811,
   0.04357482813326283,
   0.04639120786220015,
   0.04277566539923954,
   0.046337344310745196,
   0.04425900496461392,
   0.04065899250184814,
   0.0427801837963452,
   0.04604012671594509,
   0.0454065469904963,
   0.04560810810810811,
   0.04615059668391593,
   0.045094518956595206,
   0.04849445324881141,
   0.048870593202448805,
   0.04696074292950612,
   0.04466265441875198,
   0.04296875,
   0.04302325581395349,
   0.04257791864764923,
   0.04612137203166227,
   0.04387355957289354,
   0.04116529449018366,
   0.04819786491914174,
   0.04127084652733798,
   0.04093258782572001,
   0.047608993982898765,
   0.04454766177557268,
   0.04437869822485207,
   0.043492029979942996,
   0.046356916578669485,
   0.040372014373282604,
   0.04731228218396874,
   0.04579508283211987,
   0.044465568229826787,
   0.043616010138346185,
   0.0449556775010553,
   0.047071240105540896,
   0.043827225683810325,
   0.04616522290302134,
   0.04637160663356924,
   0.04405239805620114,
   0.047966191230850504,
   0.04109878499735869,
   0.046482146630044366,
   0.045099281791297,
   0.04645760743321719,
   0.04762407602956705,
   0.049133558748943366,
   0.04222527182518737,
   0.040452049007182085,
   0.0465288035450517,
   0.043909647456195904,
   0.04467680608365019,
   0.04447026513150945,
   0.04468152529840499,
   0.04392819429778247,
   0.043198141106886356,
   0.0461408510188998,
   0.04724159797083069,
   0.044993662864385296,
   0.044667370644139386,
   0.041921858500527986,
   0.05133622055561424,
   0.04643309413254538,
   0.04656319290465632,
   0.04364366479974638,
   0.043198141106886356,
   0.04648705758055996,
   0.0461408510188998,
   0.04425433037600338,
   0.045747490755414684,
   0.048981315317217354,
   0.042198544150226815,
   0.05195353748680042,
   0.04617497886728656,
   0.047417889956700814,
   0.04649196956889264,
   0.044139387539598736,
   0.042899408284023666,
   0.04706627268889827,
   0.046538623891937525,
   0.044730456799240426,
   0.0471110172177036,
   0.04083570750237417,
   0.04653371320037987,
   0.04204965662968833,
   0.044317822095599875,
   0.04490227152667723,
   0.04434589800443459,
   0.04696074292950612,
   0.04625131995776135,
   0.048553937090985856,
   0.04327176781002638,
   0.044167371090448014,
   0.0458144199303283,
   0.04591998310989127,
   0.04254196136387628,
   0.04080769637382387,
   0.046275752773375596,
   0.04447026513150945,
   0.044528859343674156,
   0.044350580781414996,
   0.04317534044125409,
   0.04530095036958817,
   0.046713168463326994,
   0.04426368054088316,
   0.044869087837837836,
   0.04520012672932728,
   0.0458144199303283,
   0.046265976550121476,
   0.0483377308707124,
   0.04389111626925512,
   0.04193514312876307,
   0.045080236486486486,
   0.0427711479564896,
   0.04395604395604396,
   0.04458531431590069,
   0.045598480050664976,
   0.04669342911472639,
   0.043625224463927324,
   0.043482849604221635,
   0.04542093588253935,
   0.04373547432917811,
   0.043841115571519124,
   0.039472295514511875,
   0.04476823989019111,
   0.04508975712777191,
   0.045771670190274845,
   0.04753855905345447,
   0.04655336218726908,
   0.04700538713425584,
   0.04835814591912153,
   0.04716184849124288,
   0.04656319290465632,
   0.04721166032953105,
   0.04401984587775784,
   0.048288250211327134,
   0.03969175551567613,
   0.04816731805218126,
   0.047699451245251163,
   0.04474934036939314,
   0.04321183306920232,
   0.044423340719637015,
   0.043850380388841925,
   0.0484688489968321,
   0.04542573420663427,
   0.04478242501056189,
   0.04871090448013525,
   0.04395604395604396,
   0.04853856705708558,
   0.04492600422832981,
   0.0436298330868371,
   0.04553137544897528,
   0.047140894197230734,
   0.042986903253062946,
   0.046131109469017204,
   0.04233083500475034,
   0.04457118715673849,
   0.045007923930269415,
   0.04712595097210482,
   0.042665540183757525,
   0.05070244005492764,
   0.04287675572922167,
   0.04743291781111346,
   0.04424965677473862,
   0.04580474934036939,
   0.044418653724414434,
   0.044291754756871034,
   0.04537281861448969,
   0.04666877837609545,
   0.042923433874709975,
   0.0430970740466885,
   0.0452240067624683,
   0.04232189973614776,
   0.04628064243448859,
   0.04752349772943289,
   0.04033365008974765,
   0.04520012672932728,
   0.04363905325443787,
   0.050459199831098915,
   0.04307887234716503,
   0.04634712837837838,
   0.05013192612137203,
   0.044648511716276124,
   0.04233083500475034,
   0.04469568892645816,
   0.0438957475994513,
   0.044350580781414996,
   0.045699208443271765,
   0.047714557162461736,
   0.04364366479974638,
   0.04340021119324182,
   0.043101626875132054,
   0.044153374881166156,
   0.04582409460458241,
   0.04331290935981407,
   0.04783526927138332,
   0.04817240650750053,
   0.04471458773784355,
   0.04634223582814315,
   0.04645760743321719,
   0.04302780420763294,
   0.04431314623338257,
   0.0433910472972973,
   0.04835304054054054,
   0.04144201289776932,
   0.045185810810810814,
   0.04392355611867807,
   0.04526271365266934,
   0.04403844122927447,
   0.04340479459288204,
   0.04710604140261935,
   0.046337344310745196,
   0.04645760743321719,
   0.04678918462188424,
   0.04391891891891892,
   0.04206298879729444,
   0.0483377308707124,
   0.04366673715373229,
   0.04965138390027467,
   0.042744063324538256,
   0.04216867469879518,
   0.04634223582814315,
   0.04573299535276722,
   0.04363905325443787,
   0.04184277261200338,
   0.04550733819026502,
   0.04285865090256519,
   0.047815072830905636,
   0.041697455927372534,
   0.04784537389100127,
   0.04424965677473862,
   0.04277566539923954,
   0.044493764531811454,
   0.0426430230103441,
   0.04636670891423743,
   0.043198141106886356,
   0.040452049007182085,
   0.04749841671944269,
   0.047714557162461736,
   0.04530573450205935,
   0.04678424332030837,
   0.04643309413254538,
   0.04492600422832981,
   0.0444796619123085,
   0.04539695945945946,
   0.04665892536683205,
   0.04946213878928496,
   0.0444796619123085,
   0.04570885675076533,
   0.046356916578669485,
   0.048579575456753614,
   0.046265976550121476,
   0.044869087837837836,
   0.04496042216358839,
   0.04698057432432432,
   0.046265976550121476,
   0.04104241401139481,
   0.04424031253299546,
   0.04646742000211215,
   0.04318445781860416,
   0.04002957329953528,
   0.04433653541644674,
   0.04466265441875198,
   0.046950833509179155,
   0.04561774023231257,
   0.04438338793194547,
   0.04680896027049873,
   0.047277332207682564,
   0.04121750158528852,
   0.040962837837837836,
   0.046275752773375596,
   0.046749683410721825,
   0.04591029023746702,
   0.0466786355475763,
   0.04564666103127642,
   0.045185810810810814,
   0.04584829917599831,
   0.04517150395778364,
   0.043841115571519124,
   0.04858470637938318,
   0.04668356569497254,
   0.04519058177594763,
   0.043060686015831136,
   0.04358379062895736,
   0.04656319290465632,
   0.043675493195484756,
   0.0436298330868371,
   0.04649688259537145,
   0.04624155405405406,
   0.04425433037600338,
   0.04642819457634272,
   0.04825765575501584,
   0.03929024081115336,
   0.044763513513513514,
   0.04347367310330273,
   0.04540175271882589,
   0.04593453009503696,
   0.04573299535276722,
   0.04300052826201796,
   0.043740095087163235,
   0.04256442754541614,
   0.041807432432432436,
   0.043942114714270626,
   0.04554580999682976,
   0.0446108415946003,
   0.04583861427967892,
   0.04410678484752559,
   0.04784537389100127,
   0.04009707713411417,
   0.0436298330868371,
   0.04230404051060238,
   0.0477447977183902,
   0.04223418857565199,
   0.04357919172733987,
   0.04581925675675676,
   0.045185810810810814,
   0.04432249894470241,
   0.04542093588253935,
   0.04478715538185275,
   0.04615059668391593,
   0.043381887270424316,
   0.04300961640071859,
   0.04689975705080807,
   0.04552175749894381,
   0.0426430230103441,
   0.040320878192949126,
   0.04750844594594594,
   0.046602557328542744,
   0.04708614864864865,
   0.04380409541904159,
   0.04793580403336501,
   0.046155471060414024,
   0.04456648009293484,
   0.044493764531811454,
   0.04767932489451477,
   0.04425900496461392,
   0.046356916578669485,
   0.04731727925644275,
   0.046975614905520956,
   0.049182058047493406,
   0.044148711449091674,
   0.04786053882725832,
   0.04865948912814017,
   0.04808200359294093,
   0.04677436384753458,
   0.04422630356765886,
   0.04784537389100127,
   0.04708614864864865,
   0.04835814591912153,
   0.044648511716276124,
   0.044465568229826787,
   0.04582893347412883,
   0.04991557619248628,
   0.04400590966652596,
   0.04931882986587813,
   0.04289487585842578,
   0.04045632196049435,